# Generated by Django 5.0.1 on 2024-01-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_userdetails_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
