# Generated by Django 5.0.1 on 2024-01-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0004_answer_evaluvated_at_answer_evaluvated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
